language: python
cache: pip
python:
  - "3.5"
  - "3.6"
sudo: required
services:
 - postgresql


branches:
  only:
    - master
    - develop
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python manage.py collectstatic
  - psql -U postgres -c "CREATE USER flutype_user WITH CREATEUSER PASSWORD 'flutype_test';"
  - psql -U postgres -c "ALTER USER flutype_user CREATEDB;"
  #- psql -U postgres -c "CREATE DATABASE flutype_test;"
  # clean setup
  - python manage.py makemigrations
  - python manage.py makemigrations flutype
  - python manage.py migrate


script:
- coverage run --source='.' manage.py test flutype --exclude-tag=local
after_success:
  coveralls
