language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: required

branches:
  only:
    - master
    - develop
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  python manage.py collectstatic
script:
- coverage run --source='.' manage.py test flutype
after_success:
  coveralls
