language: python
cache: pip
python:
  - "3.5"
  - "3.6"
sudo: required

branches:
  only:
    - master
    - develop
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python manage.py collectstatic
  - psql -c "CREATE DATABASE flutype with owner flutype_user;" -U postgres
script:
- coverage run --source='.' manage.py test flutype --exclude-tag=local
after_success:
  coveralls
