language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: required

branches:
  only:
    - master
    - develop

install:
  pip install -r requirements.txt
before_script:

  python manage.py collectstatic
script:
 coverage run --source='.' manage.py test flutype --exclude-tag=local

after_success:
  - coveralls
