language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: required

branches:
  only:
    - master
    - develop

install:
  pip install -r requirements.txt
  python manage.py collectstatic

script:
  python manage.py test

# after_success:
#   pip install codecov; codecov
