language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: required

branches:
  only:
    - master
    - develop

install:
  pip install -r requirements.txt

script:
  python manage.py collectstatic && coverage run --source='.' manage.py test flutype --noinput

after_success:

after_success:
  - coveralls
