language: python
cache: pip
python:
  - "3.5"
  - "3.6"
sudo: required
services:
 - postgresql


branches:
  only:
    - master
    - develop
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python manage.py collectstatic
  - psql -c "CREATE DATABASE flutype;" -U flutype_user
script:
- coverage run --source='.' manage.py test flutype --exclude-tag=local
after_success:
  coveralls
