##################################
# Connects django with postgres
##################################
# available at 0.0.0.0:8000
version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    command: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db