# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 14:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pH', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('purity', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('production_date', models.DateField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Peptide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('linker', models.CharField(blank=True, max_length=50)),
                ('spacer', models.CharField(blank=True, max_length=50)),
                ('sequence', models.CharField(blank=True, max_length=50)),
                ('c_terminus', models.CharField(blank=True, max_length=50)),
                ('blank', models.BooleanField()),
                ('reference', models.BooleanField()),
                ('antibody', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Peptide_batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('concentration', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('strain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Virus_batch',
            fields=[
                ('batch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flutype.Batch')),
                ('passage_history', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('labeling', models.CharField(blank=True, max_length=50)),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flutype.Virus')),
            ],
            bases=('flutype.batch',),
        ),
        migrations.AddField(
            model_name='peptide_batch',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flutype.Batch'),
        ),
        migrations.AddField(
            model_name='peptide_batch',
            name='peptide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flutype.Peptide'),
        ),
        migrations.AddField(
            model_name='batch',
            name='buffer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flutype.Buffer'),
        ),
        migrations.AddField(
            model_name='batch',
            name='produced_by',
            field=models.ManyToManyField(blank=True, to='flutype.User'),
        ),
    ]
