# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peptite_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_types', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='peptide',
            name='antibody',
        ),
        migrations.RemoveField(
            model_name='peptide',
            name='blank',
        ),
        migrations.RemoveField(
            model_name='peptide',
            name='reference',
        ),
    ]
