"""
Django settings for flutype_webapp project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from __future__ import absolute_import, print_function
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f$h*w&tw*vqk=sg306mc0t(kd*cuhgu57_xfo=t@4h4a0&no+8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0', 'localhost', 'flutype.de', 'www.flutype.de', 'testserver']

# SECURITY WARNING: don't run create users with default password in production !
DEFAULT_USER_PASSWORD = 'flutype_db'

#AUTHENTICATION_BACKENDS = (
#    'django.contrib.auth.backends.ModelBackend', # this is default
#    'guardian.backends.ObjectPermissionBackend',
#)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'flutype.apps.FlutypeConfig',
    'debug_toolbar',
    'polymorphic',
    'imagekit',
    'rest_framework',
    #'guardian',
    'dbbackup',  # django-dbbackup
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'flutype_webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [os.path.join(BASE_DIR, 'flutype/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'flutype_webapp.jinja2.environment',

        },
    },

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
            ],
        },
    },
]

WSGI_APPLICATION = 'flutype_webapp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'media/db.sqlite3'),
    },

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'flutype',
    #     'USER': 'flutype_user',
    #     'HOST': 'localhost',
    #     'PASSWORD': 'flutype_test',
    #     'PORT': 5432,
    #     'TEST':{
    #         'NAME': 'test_flutype',
    #     },
    # }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# for djange debug toolbar
INTERNAL_IPS = ['127.0.0.1', ]

LOGIN_REDIRECT_URL = '/index'
LOGIN_URL = '/login/'

# Database backup
# sudo mkdir -p /var/backups/flutypedb
# sudo chown -R mkoenig:mkoenig /var/backups/flutypedb
# python manage.py dbbackup
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/var/backups/flutypedb'}


######################################################################################
# Overwrite settings for the deployment
######################################################################################
# The deploy_settings.py is only on the server and not tracked via
# the version control !
######################################################################################
try:
    from flutype_webapp.deploy_settings import *

    print("*" * 40)
    print("RUNNING IN DEPLOYMENT")
    print("*" * 40)
except ImportError as e:
    print("*" * 40)
    print("RUNNING IN DEVELOP")
    print("*" * 40)


